import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { BalancedResult, ReactionType, Step } from '@/types/chemistry'

// Extend Window interface for export result
declare global {
  interface Window {
    __exportResult__?: BalancedResult
  }
}

/**
 * Convert equation to LaTeX format
 */
export function toLatex(result: BalancedResult): string {
  // Convert chemical formulas to LaTeX chemistry notation
  const formatChemFormula = (formula: string): string => {
    // Replace numbers with subscripts: H2O → H_2O
    return formula.replace(/(\d+)/g, '_{$1}')
  }

  const balanced = result.balanced
    .split(' ')
    .map(part => {
      if (part === '+' || part === '→' || part === '->') {
        return part === '→' || part === '->' ? '\\rightarrow' : '+'
      }
      return `\\text{${formatChemFormula(part)}}`
    })
    .join(' ')

  return `\\ce{${balanced}}`
}

/**
 * Export equation as JSON
 */
export function toJSON(result: BalancedResult): string {
  const exportData = {
    original: result.original,
    balanced: result.balanced,
    coefficients: result.coefficients,
    metadata: result.metadata,
    steps: result.steps,
    exportedAt: new Date().toISOString(),
  }

  return JSON.stringify(exportData, null, 2)
}

/**
 * Download JSON file
 */
export function downloadJSON(result: BalancedResult, filename: string = 'equation.json'): void {
  const jsonString = toJSON(result)
  const blob = new Blob([jsonString], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Get unique elements from balanced equation
 */
function getUniqueElements(result: BalancedResult): string[] {
  const elements = new Set<string>()
  result.balanced.split(/[\s→+\-]/).forEach(compound => {
    if (compound && /^[A-Z]/.test(compound)) {
      const matches = compound.match(/[A-Z][a-z]?/g)
      if (matches) {
        matches.forEach(match => elements.add(match))
      }
    }
  })
  return Array.from(elements)
}

/**
 * Download LaTeX file with enhanced formatting
 */
export function downloadLatex(result: BalancedResult, filename: string = 'equation.tex'): void {
  const stepsList = result.steps.map((step: Step, index: number) => {
    const number = index + 1
    return `\\item[${number}] \\textbf{${step.title}}: ${step.description.replace(/\n/g, ' ')}`
  }).join('\n')

  const uniqueElements = getUniqueElements(result)

  const latexString = `% Chemical Equation Export
% Generated by Chemical Equation Balancer
% Date: ${new Date().toLocaleDateString()}

\\documentclass[12pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{mhchem}
\\usepackage{amsmath}
\\usepackage[margin=1in]{geometry}
\\usepackage{enumitem}

\\title{Chemical Equation: ${result.balanced.replace(/\s+/g, ' ')}}
\\author{Chemical Equation Balancer}

\\begin{document}

\\mktitle

\\section*{Original Equation}
\\begin{center}
\\ce{${result.original}}
\\end{center}

\\section*{Balanced Equation}
\\begin{center}
\\ce{${result.balanced}}
\\end{center}

\\section*{Reaction Information}
\\begin{itemize}
  \\item \\textbf{Type:} ${result.metadata?.reactionType || 'Unknown'}
  \\item \\textbf{Elements:} ${uniqueElements.join(', ') || 'N/A'}
\\end{itemize}

\\section*{Coefficients}
\\begin{center}
[${result.coefficients.join(', ')}]
\\end{center}

\\section*{Solution Steps}
\\begin{enumerate}[label=\\arabic*.]
${stepsList}
\\end{enumerate}

\\section*{Molecular Weights}
\\begin{center}
\\begin{tabular}{|c|c|}
\\hline
Compound & Molecular Weight (g/mol) \\\\ \\hline
${result.metadata?.molecularWeights ? result.metadata.molecularWeights.map((mw) => `${mw.compound} & ${mw.weight.toFixed(3)}`).join('\\\\ \\hline') : 'N/A'} \\\\
\\hline
\\end{tabular}
\\end{center}

\\bigskip
\\begin{center}
\\textit{Exported on ${new Date().toLocaleString()}}
\\end{center}

\\end{document}
`

  const blob = new Blob([latexString], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Export element as PNG using html2canvas with enhanced styling
 */
export async function exportToPNG(
  elementId: string,
  filename: string = 'equation.png'
): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`)
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2,
    logging: false,
    useCORS: true,
  })

  canvas.toBlob((blob) => {
    if (!blob) {
      throw new Error('Failed to create blob')
    }
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  })
}

/**
 * Export element as PDF using jsPDF with enhanced formatting
 */
export async function exportToPDF(
  elementId: string,
  filename: string = 'equation.pdf'
): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`)
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2,
    logging: false,
    useCORS: true,
  })

  const imgData = canvas.toDataURL('image/png')
  
  // Create PDF with A4 size
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 15
  const maxWidth = pageWidth - (margin * 2)

  // Add header with branding
  pdf.setFillColor(15, 23, 42) // Slate 900
  pdf.rect(0, 0, pageWidth, 35, 'F')

  pdf.setFontSize(20)
  pdf.setTextColor(255, 255, 255)
  pdf.text('Chemical Equation Balancer', pageWidth / 2, 15, { align: 'center' })

  pdf.setFontSize(10)
  pdf.setTextColor(203, 213, 225)
  pdf.text('Balanced Chemical Equation Export', pageWidth / 2, 25, { align: 'center' })

  // Add the image
  const imgWidth = maxWidth
  const imgHeight = (canvas.height * imgWidth) / canvas.width
  const imgY = 45

  pdf.addImage(imgData, 'PNG', margin, imgY, imgWidth, imgHeight)

  // Add footer
  const footerY = pageHeight - margin - 5
  pdf.setFontSize(8)
  pdf.setTextColor(148, 163, 184)
  pdf.text(`Exported on ${new Date().toLocaleString()}`, pageWidth / 2, footerY, { align: 'center' })

  pdf.save(filename)
}

/**
 * Copy LaTeX to clipboard
 */
export async function copyLatexToClipboard(result: BalancedResult): Promise<void> {
  const latex = toLatex(result)
  await navigator.clipboard.writeText(latex)
}

/**
 * Copy JSON to clipboard
 */
export async function copyJSONToClipboard(result: BalancedResult): Promise<void> {
  const json = toJSON(result)
  await navigator.clipboard.writeText(json)
}
