import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { BalancedResult } from '@/types/chemistry'

/**
 * Convert equation to LaTeX format
 */
export function toLatex(result: BalancedResult): string {
  // Convert chemical formulas to LaTeX chemistry notation
  const formatChemFormula = (formula: string): string => {
    // Replace numbers with subscripts: H2O → H_2O
    return formula.replace(/(\d+)/g, '_{$1}')
  }

  const balanced = result.balanced
    .split(' ')
    .map(part => {
      if (part === '+' || part === '→' || part === '->') {
        return part === '→' || part === '->' ? '\\rightarrow' : '+'
      }
      return `\\text{${formatChemFormula(part)}}`
    })
    .join(' ')

  return `\\ce{${balanced}}`
}

/**
 * Export equation as JSON
 */
export function toJSON(result: BalancedResult): string {
  const exportData = {
    original: result.original,
    balanced: result.balanced,
    coefficients: result.coefficients,
    metadata: result.metadata,
    steps: result.steps,
    exportedAt: new Date().toISOString(),
  }

  return JSON.stringify(exportData, null, 2)
}

/**
 * Download JSON file
 */
export function downloadJSON(result: BalancedResult, filename: string = 'equation.json'): void {
  const jsonString = toJSON(result)
  const blob = new Blob([jsonString], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Download LaTeX file
 */
export function downloadLatex(result: BalancedResult, filename: string = 'equation.tex'): void {
  const latexString = `% Chemical Equation
% Generated by Chemical Equation Balancer

\\documentclass{article}
\\usepackage{mhchem}

\\begin{document}

\\section*{Balanced Chemical Equation}

Original: ${toLatex({ ...result, balanced: result.original })}

Balanced: ${toLatex(result)}

\\section*{Step-by-Step Solution}

\\begin{enumerate}
${result.steps.map(step => `  \\item \\textbf{${step.title}}: ${step.description.replace(/\n/g, ' ')}`).join('\n')}
\\end{enumerate}

\\end{document}
`

  const blob = new Blob([latexString], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Export element as PNG using html2canvas
 */
export async function exportToPNG(
  elementId: string,
  filename: string = 'equation.png'
): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`)
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2, // Higher resolution
  })

  canvas.toBlob((blob) => {
    if (!blob) {
      throw new Error('Failed to create blob')
    }
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  })
}

/**
 * Export element as PDF using jsPDF and html2canvas
 */
export async function exportToPDF(
  elementId: string,
  filename: string = 'equation.pdf'
): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`)
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2,
  })

  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const imgWidth = 190
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight)
  pdf.save(filename)
}

/**
 * Copy LaTeX to clipboard
 */
export async function copyLatexToClipboard(result: BalancedResult): Promise<void> {
  const latex = toLatex(result)
  await navigator.clipboard.writeText(latex)
}

/**
 * Copy JSON to clipboard
 */
export async function copyJSONToClipboard(result: BalancedResult): Promise<void> {
  const json = toJSON(result)
  await navigator.clipboard.writeText(json)
}
